name: Static Hosting Pipeline

# Trigger on pushes to main (and optionally on pull‑request merges)
on:
  push:
    # Trigger on pushes to any branch
    branches: ['**']
  pull_request:
    # Trigger on pull requests from any branch
    branches: ['**']

# Give the workflow explicit permissions required for Pages deployment
permissions:
  contents: read        # keep read for source operations
  pages: write          # required to deploy to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Go application
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        run: |
          cd docs
          chmod +x wasm_compile_all.sh
          ls -lah
          ./wasm_compile_all.sh

      # Upload the generated static site as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1